export default {
  cars: [
    {
      id: 1,
      title: 'BMW 328',
      img: 'bmw_328_cabrio/IMG_9966.jpg',
      description: 'cabrio',
      price: '45-90 $',
      photos: [
        'bmw_328_cabrio/IMG_9966.jpg',
        'bmw_328_cabrio/IMG_9929.jpg',
        'bmw_328_cabrio/IMG_9933.jpg',
        'bmw_328_cabrio/IMG_9936.jpg',
        'bmw_328_cabrio/IMG_9938.jpg',
        'bmw_328_cabrio/IMG_9939.jpg',
        'bmw_328_cabrio/IMG_9943.jpg',
        'bmw_328_cabrio/IMG_9945.jpg',
        'bmw_328_cabrio/IMG_9949.jpg',
        'bmw_328_cabrio/IMG_9952.jpg',
        'bmw_328_cabrio/IMG_9966.jpg'
      ],
      info: [
        { title: 'Engine', value: '3L'},
        { title: 'Transmission', value: 'Auto'},
        { title: 'Year', value: '2011'},
        { title: 'Audio', value: 'Radio, Audio-CD, MP3, AUX'},
        { title: 'Seats', value: '4'},
        { title: 'Drive', value: 'Back'},
        { title: 'Сabrio', value: 'Yes'},
        { title: 'Left-hand drive', value: 'Yes'},
        { title: 'Interior material', value: 'Leather'},
        { title: 'ABS', value: 'Yes'},
        { title: 'EBD', value: 'Yes'},
        { title: 'ESP', value: 'Yes'},
        { title: 'Cruise control', value: 'Yes'},
        { title: 'Parktronic', value: 'No'},
        { title: 'Rear View Camera', value: 'No'},
        { title: '1-2 days', value: '90$ per day'},
        { title: '3-6 days', value: '65$ per day'},
        { title: '7-12 days', value: '60$ per day'},
        { title: '13-30 days', value: '50$ per day'},
        { title: '30+ days', value: '45$ per day'},
      ]
    },
    {
      id: 2,
      title: 'Mercedes GL',
      img: 'mercedes_gl/IMG_0051.jpg',
      description: '4x4',
      price: '28-70 $',
      photos: [
        'mercedes_gl/IMG_0051.jpg',
        'mercedes_gl/IMG_0054.jpg',
        'mercedes_gl/IMG_0058.jpg',
        'mercedes_gl/IMG_0064.jpg',
        'mercedes_gl/IMG_0068.jpg',
        'mercedes_gl/IMG_0073.jpg',
        'mercedes_gl/IMG_0079.jpg',
        'mercedes_gl/IMG_0082.jpg',
        'mercedes_gl/IMG_0091.jpg'
      ],
      info: [
        { title: 'Engine', value: '3L'},
        { title: 'Transmission', value: 'Auto'},
        { title: 'Year', value: '2007'},
        { title: 'Audio', value: 'Radio, Audio-CD, AUX, Bluetooth'},
        { title: 'Seats', value: '7'},
        { title: 'Drive', value: '4x4'},
        { title: 'Сabrio', value: 'No'},
        { title: 'Left-hand drive', value: 'Yes'},
        { title: 'Interior material', value: 'Leather'},
        { title: 'ABS', value: 'Yes'},
        { title: 'EBD', value: 'Yes'},
        { title: 'ESP', value: 'Yes'},
        { title: 'Cruise control', value: 'Yes'},
        { title: 'Parktronic', value: 'Yes'},
        { title: 'Rear View Camera', value: 'Yes'},
        { title: '1-2 days', value: '70$ per day'},
        { title: '3-6 days', value: '50$ per day'},
        { title: '7-12 days', value: '40$ per day'},
        { title: '13-30 days', value: '30$ per day'},
        { title: '30+ days', value: '28$ per day'},
      ]
    },
    {
      id: 3,
      title: 'VW Routan',
      img: 'vw_routan/IMG_0099.jpg',
      description: 'bus',
      price: '25-68 $',
      photos: [
        'vw_routan/IMG_0099.jpg',
        'vw_routan/IMG_0102.jpg',
        'vw_routan/IMG_0104.jpg',
        'vw_routan/IMG_0106.jpg',
        'vw_routan/IMG_0108.jpg',
        'vw_routan/IMG_0117.jpg',
        'vw_routan/IMG_0125.jpg',
        'vw_routan/IMG_0128.jpg',
        'vw_routan/IMG_0131.jpg'
      ],
      info: [
        { title: 'Engine', value: '3.6L'},
        { title: 'Transmission', value: 'Auto'},
        { title: 'Year', value: '2007'},
        { title: 'Audio', value: 'Radio, Audio-CD, MP3, USB, AUX, Bluetooth'},
        { title: 'Seats', value: '7'},
        { title: 'Drive', value: '4x4'},
        { title: 'Сabrio', value: 'No'},
        { title: 'Left-hand drive', value: 'Yes'},
        { title: 'Interior material', value: 'Leather'},
        { title: 'ABS', value: 'Yes'},
        { title: 'EBD', value: 'Yes'},
        { title: 'ESP', value: 'Yes'},
        { title: 'Cruise control', value: 'Yes'},
        { title: 'Parktronic', value: 'No'},
        { title: 'Rear View Camera', value: 'Yes'},
        { title: '1-2 days', value: '68$ per day'},
        { title: '3-6 days', value: '50$ per day'},
        { title: '7-12 days', value: '40$ per day'},
        { title: '13-30 days', value: '33$ per day'},
        { title: '30+ days', value: '25$ per day'},
      ]
    },
    {
      id: 4,
      title: 'BMW F10',
      img: 'bmw_f10/IMG_0004.jpg',
      description: 'sport',
      price: '55-100 $',
      photos: [
        'bmw_f10/IMG_0004.jpg',
        'bmw_f10/IMG_0010.jpg',
        'bmw_f10/IMG_0013.jpg',
        'bmw_f10/IMG_0016.jpg',
        'bmw_f10/IMG_0017.jpg',
        'bmw_f10/IMG_0023.jpg',
        'bmw_f10/IMG_0029.jpg',
        'bmw_f10/IMG_0030.jpg',
        'bmw_f10/IMG_9976.jpg',
        'bmw_f10/IMG_9994.jpg',
        'bmw_f10/IMG_9999.jpg'
      ],
      info: [
        { title: 'Engine', value: '3L'},
        { title: 'Transmission', value: 'Auto'},
        { title: 'Year', value: '2015'},
        { title: 'Audio', value: 'Radio, Audio-CD, MP3, USB, AUX, Bluetooth'},
        { title: 'Seats', value: '7'},
        { title: 'Drive', value: '4x4'},
        { title: 'Сabrio', value: 'No'},
        { title: 'Left-hand drive', value: 'Yes'},
        { title: 'Interior material', value: 'Leather'},
        { title: 'ABS', value: 'Yes'},
        { title: 'EBD', value: 'Yes'},
        { title: 'ESP', value: 'Yes'},
        { title: 'Cruise control', value: 'Yes'},
        { title: 'Parktronic', value: 'Yes'},
        { title: 'Rear View Camera', value: 'Yes'},
        { title: '1-2 days', value: '100$ per day'},
        { title: '3-6 days', value: '80$ per day'},
        { title: '7-12 days', value: '70$ per day'},
        { title: '13-30 days', value: '60$ per day'},
        { title: '30+ days', value: '55$ per day'},
      ]
    },
    {
      id: 5,
      title: 'Mercedes CLS',
      img: 'merc_cls/IMG_0420.jpg',
      description: 'business',
      price: '60-150 $',
      photos: [
        'merc_cls/IMG_0379.jpg',
        'merc_cls/IMG_0383.jpg',
        'merc_cls/IMG_0385.jpg',
        'merc_cls/IMG_0386.jpg',
        'merc_cls/IMG_0395.jpg',
        'merc_cls/IMG_0400.jpg',
        'merc_cls/IMG_0420.jpg',
        'merc_cls/IMG_0423.jpg',
        'merc_cls/IMG_0425.jpg',
        'merc_cls/IMG_0426.jpg',
        'merc_cls/IMG_0429.jpg',
        'merc_cls/IMG_0434.jpg',
        'merc_cls/IMG_0436.jpg'
      ],
      info: [
        { title: 'Engine', value: '4.7L'},
        { title: 'Transmission', value: 'Auto'},
        { title: 'Year', value: '2012'},
        { title: 'Audio', value: 'Radio, Audio-CD, MP3, Bluetooth'},
        { title: 'Seats', value: '4'},
        { title: 'Drive', value: 'RWD'},
        { title: 'Сabrio', value: 'No'},
        { title: 'Left-hand drive', value: 'Yes'},
        { title: 'Interior material', value: 'Leather'},
        { title: 'ABS', value: 'Yes'},
        { title: 'EBD', value: 'Yes'},
        { title: 'ESP', value: 'Yes'},
        { title: 'Cruise control', value: 'Yes'},
        { title: 'Parktronic', value: 'Yes'},
        { title: 'Rear View Camera', value: 'Yes'},
        { title: '1-2 days', value: '150$ per day'},
        { title: '3-6 days', value: '115$ per day'},
        { title: '7-12 days', value: '95$ per day'},
        { title: '13-30 days', value: '70$ per day'},
        { title: '30+ days', value: '60$ per day'},
      ]
    },
    {
      id: 6,
      title: 'FIAT 500',
      img: 'fiat_500/IMG_0294.jpg',
      description: 'gucci',
      price: '20-50 $',
      photos: [
        'fiat_500/IMG_0294.jpg',
        'fiat_500/IMG_0306.jpg',
        'fiat_500/IMG_0308.jpg',
        'fiat_500/IMG_0311.jpg',
        'fiat_500/IMG_0313.jpg',
        'fiat_500/IMG_0314.jpg',
        'fiat_500/IMG_0317.jpg',
        'fiat_500/IMG_0321.jpg',
        'fiat_500/IMG_0323.jpg',
        'fiat_500/IMG_0325.jpg',
        'fiat_500/IMG_0326.jpg',
        'fiat_500/IMG_0332.jpg',
        'fiat_500/IMG_0335.jpg'
      ],
      info: [
        { title: 'Engine', value: '1.4L'},
        { title: 'Transmission', value: 'Auto'},
        { title: 'Year', value: '2013'},
        { title: 'Audio', value: 'Audio-CD, Radio, USB, AUX'},
        { title: 'Seats', value: '4'},
        { title: 'Drive', value: 'FWD'},
        { title: 'Сabrio', value: 'Yes'},
        { title: 'Left-hand drive', value: 'Yes'},
        { title: 'Interior material', value: 'Leather'},
        { title: 'ABS', value: 'Yes'},
        { title: 'EBD', value: 'Yes'},
        { title: 'ESP', value: 'Yes'},
        { title: 'Cruise control', value: 'Yes'},
        { title: 'Parktronic', value: 'Yes'},
        { title: 'Rear View Camera', value: 'No'},
        { title: '1-2 days', value: '50$ per day'},
        { title: '3-6 days', value: '35$ per day'},
        { title: '7-12 days', value: '25$ per day'},
        { title: '13-30 days', value: '23$ per day'},
        { title: '30+ days', value: '20$ per day'},
      ]
    },
    {
      id: 7,
      title: 'Mustang',
      img: 'mustang_black/IMG_0337.jpg',
      description: 'muscle',
      price: '45-90 $',
      photos: [
        'mustang_black/IMG_0337.jpg',
        'mustang_black/IMG_0342.jpg',
        'mustang_black/IMG_0351.jpg',
        'mustang_black/IMG_0354.jpg',
        'mustang_black/IMG_0360.jpg',
        'mustang_black/IMG_0363.jpg',
        'mustang_black/IMG_0372.jpg',
        'mustang_black/IMG_0373.jpg',
        'mustang_black/IMG_0379.jpg',
        'mustang_black/IMG_0383.jpg',
        'mustang_black/IMG_0385.jpg',
        'mustang_black/IMG_0386.jpg',
        'mustang_black/IMG_0395.jpg'
      ],
      info: [
        { title: 'Engine', value: '3.7L'},
        { title: 'Transmission', value: 'Auto'},
        { title: 'Year', value: '2012'},
        { title: 'Audio', value: 'Radio, Audio-CD, MP3, AUX, Bluetooth'},
        { title: 'Seats', value: '4'},
        { title: 'Drive', value: 'AWD'},
        { title: 'Сabrio', value: 'Yes'},
        { title: 'Left-hand drive', value: 'Yes'},
        { title: 'Interior material', value: 'Leather'},
        { title: 'ABS', value: 'Yes'},
        { title: 'EBD', value: 'Yes'},
        { title: 'ESP', value: 'Yes'},
        { title: 'Cruise control', value: 'Yes'},
        { title: 'Parktronic', value: 'Yes'},
        { title: 'Rear View Camera', value: 'No'},
        { title: '1-2 days', value: '90$ per day'},
        { title: '3-6 days', value: '75$ per day'},
        { title: '7-12 days', value: '65$ per day'},
        { title: '13-30 days', value: '55$ per day'},
        { title: '30+ days', value: '45$ per day'},
      ]
    },
  ]
}
